apiVersion: apps/v1
kind: Deployment
metadata:
  name: reception-api
  labels:
    app: reception-api
spec:
  replicas: 1 # TODO create way for multiple replicas to share incoming messages
  selector:
    matchLabels:
      app: reception-api
  template:
    metadata:
      name: reception-api
      labels:
        app: reception-api
    spec:
      containers:
        - name: reception-api-api
          image: accio1/gochat:v1.0
          imagePullPolicy: Always
          env:
            - name: RECEPTIONAPI_PORT
              value: ":8888"
            - name: RECEPTIONAPI_MAX_CONNECTIONS
              value: "3"
      restartPolicy: Always

---
apiVersion: v1
kind: Service
metadata:
  name: reception-api
  labels:
    app: reception-api
spec:
  selector:
    app: reception-api
  type: NodePort
  ports:
    - port: 80
      name: http
      targetPort: 8888

