version: "3"
services:
  reception_api:
    image: accio1/receptionapi:v1.0
    ports:
      - "8080:8080"
    environment:
      RECEPTIONAPI_PORT: ":8080"
      RECEPTIONAPI_: ":8080"
    depends_on:
      - rabbitmq

  dispatcher_api:
    image: accio1/dispatcherapi:v1.0
    ports:
      - "8799:8799"
    environment:
      DISPATCHERAPI_PORT: ":8799"
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3.13-management
    ports:
      - "5672:5672"
      - "15672:15672"
